"""add new column to show: start_time

Revision ID: 063402a21688
Revises: 0efb7ecfbd3f
Create Date: 2022-08-16 12:59:20.388406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063402a21688'
down_revision = '0efb7ecfbd3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###
